### ISSUE TITLE
Using DessedDilated with custom dataset

### ISSUE THREAD

**Issue by SrijithBalachander** [dr-costas/dnd-sed#2]
Hey authors,

I was wondering how I could transfer the dessedDilated model to train with my pipeline using my custom datasets and dataloader. I have tried looking through files in the model directory, the settings files, _process.py etc. and I seem to be getting somewhere but its still not clear to me. What changes do I have to make to simply use the dessedDilated model?

Thanks

**Comment by dr-costas** [comment]
Hey!

I can see two ways of treating this. The first is by using a custom data loader (with the appropriate dataset scripts), and the second by getting the files for the `dessed_dilated` and use them in your own system. 

----

To do the first one, you have to modify the file `experiments/_processes.py`, at lines 257 to 260: 

```python
with InformAboutProcess('Creating training data loader'):
        training_data = get_tut_sed_data_loader(
            split='training',
            **settings['data_loader'])
```

and at lines 262 to 265:

```python
with InformAboutProcess('Creating validation data loader'):
        validation_data = get_tut_sed_data_loader(
            split='validation',
            **settings['data_loader'])
```

you will have to replace the function `get_tut_sed_data_loader` with your own one. 

If you have special arguments, you can add those to the `.yaml` file with the settings that you want to use, under the key `data_loader`. 

----

To do the second, you have to get the files:

  * `models/dessed_dilated.py`, 
  * `models/_modules/dessed_dnn.py`,  and
  * `models/_modules/depthwise_separable_conv_block.py`

and use these files in your own code. 

----

Let me know if the above worked! 

Cheers!

**Comment by dr-costas** [comment]
Hey,

Have you been able to use the code with your own dataloader? Shall I close the issue?

**Comment by SrijithBalachander** [comment]
Hi,

Yes I was able to run the model on my own system. Got it working just an hour ago.
Thank you. You can close the issue.

**Comment by dr-costas** [comment]
Happy to hear! I'm closing the issue.
